### PR TITLE
Updated the broken link on history page

### PR DESCRIPTION
**Pull request by co1in**
My b on the broken link. Didn't realize the house image was linked here too.

Also reduced the house image file size since 4,000px is a bit unnecessary

### CODE REVIEW

**Comment by austintrose** [comment]
Lessons learned, @co1in. Whenever you remove something, `grep` the codebase for other occurrences.

Or use a real IDE with refactoring tools that shows you that shit automatically. I recommend PyCharms for Django.

**Comment by Rdbaker** [comment]
#vim

**Comment by austintrose** [comment]
PyCharms with Vim bindings.

**Comment by Rdbaker** [comment]
Vim with python-mode plugin

**Comment by austintrose** [comment]
Aight that's pretty classy. I do kind of miss using straight up Vim. I used to have [this fuckin sweet poster](http://vimcheatsheet.com/products/vim-cheat-sheet-digital) up next to my desk and everything.

**Pull request merged**
