### PR TITLE
Added Pageview analytics to site header (applies to all pages)

### PR DESCRIPTION
**Pull request by co1in**

### CODE REVIEW

**Comment by Rdbaker** [comment]
Might be worth looking into Mixpanel. It allows for event tracking and has a pretty simple API

**Comment by timmarschall** [comment]
Agree with Baker:

Mixpanel is easier and straightforward event tracking. I feel it would be easier to learn and easier to implement

**Comment by co1in** [comment]
Goal is just to track page views on the site (considering our public site consists of static pages), which both services do equally well and have the same method of implementation on a web page. We could start a debate about which has better behavior tracking but there's no behavior or event data we're really looking for here. Just want to know on a basic level how many people are actually using the site.

**Comment by timmarschall** [comment]
That only supports min and @Rdbaker point tho. if both do page tracking equally well, why would we chose the one that makes behavior tracking harder? (Even if we don't use it right now)

**Comment by co1in** [comment]
Never said it makes behavior tracking harder. Said it wasn't worth a debate. Reasons to go with google are because it's free.

**Comment by timmarschall** [comment]
So is Mixpanel for our needs. Pricing is free up to 25000 data points. 
Google Analytics is free up to a cap.

I think Mixpanel has the simpler API.
https://www.quora.com/How-is-Mixpanel-different-from-Google-Analytics

Y'all do what y'all think is best.

**Pull request merged**
